# Generated by Django 4.2 on 2023-04-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('number_of_person', models.IntegerField(default=1)),
                ('steps', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('measure', models.CharField(choices=[('th', 'штук'), ('cup', 'стакан'), ('gr', 'грамм')], default='th', max_length=3)),
                ('dishe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dishe')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product')),
            ],
        ),
        migrations.AddField(
            model_name='dishe',
            name='products',
            field=models.ManyToManyField(through='menu.ProductDishe', to='menu.product'),
        ),
    ]
